# Generated by Django 5.2.1 on 2025-06-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(choices=[('SYSTEME', 'Système'), ('OPERATION', 'Opération bancaire'), ('UTILISATEUR', 'Utilisateur'), ('COMPTE', 'Compte bancaire')], default='SYSTEME', max_length=50, verbose_name='Sujet')),
                ('type_action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION_COMPTE', 'Création de compte'), ('VALIDATION_COMPTE', 'Validation de compte'), ('REJET_COMPTE', 'Rejet de compte'), ('VIREMENT', 'Virement'), ('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('ERREUR_SYSTEME', 'Erreur système'), ('MISE_A_JOUR_UTILISATEUR', 'Mise à jour utilisateur')], max_length=50, verbose_name="Type d'action")),
                ('visibilite', models.CharField(choices=[('PUBLIQUE', "Visible par l'utilisateur"), ('INTERNE', 'Réservé aux agents et administrateurs')], default='INTERNE', max_length=10, verbose_name='Visibilité')),
                ('identifiant_utilisateur', models.IntegerField(blank=True, null=True, verbose_name="ID de l'utilisateur concerné")),
                ('source', models.CharField(max_length=255, verbose_name='Source du message (microservice, module...)')),
                ('niveau', models.CharField(max_length=50, verbose_name='Niveau de sévérité (INFO, WARNING, ERREUR)')),
                ('message', models.TextField(verbose_name='Message de log')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
            ],
        ),
    ]
