# Generated by Django 5.2.1 on 2025-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('type_action', models.CharField(choices=[('SYSTEME', 'Système'), ('OPERATION', 'Opération bancaire'), ('UTILISATEUR', 'Utilisateur'), ('COMPTE', 'Compte bancaire'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION_COMPTE', 'Création de compte'), ('VALIDATION_COMPTE', 'Validation de compte'), ('REJET_COMPTE', 'Rejet de compte'), ('VIREMENT', 'Virement'), ('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('ERREUR_SYSTEME', 'Erreur système'), ('MISE_A_JOUR_UTILISATEUR', 'Mise à jour utilisateur')], default='SYSTEME', max_length=30)),
                ('visibilite', models.CharField(choices=[('INTERNE', 'Interne'), ('EXTERNE', 'Externe')], default='INTERNE', max_length=10)),
                ('identifiant_utilisateur', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(default='microservice', max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LogModels',
        ),
    ]
