# Generated by Django 5.2.1 on 2025-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_api', '0002_log_delete_logmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='visibilite',
            field=models.CharField(choices=[('MEMBRES', 'Membres'), ('AGENTS', 'Agents')], default='INTERNE', max_length=10),
        ),
    ]
