# Generated by Django 5.2.1 on 2025-06-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logging_api', '0003_alter_log_visibilite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='additional_data',
        ),
    ]
