# Generated by Django 5.2.1 on 2025-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_api', '0004_remove_log_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='topic',
            field=models.CharField(default='logs.default', max_length=100),
        ),
    ]
