# Generated by Django 5.2 on 2025-06-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_api', '0005_log_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='topic',
        ),
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='type_action',
            field=models.CharField(choices=[('SYSTEME', 'Système'), ('OPERATION', 'Opération bancaire'), ('UTILISATEUR', 'Utilisateur'), ('COMPTE', 'Compte bancaire'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION_COMPTE', 'Création de compte'), ('VALIDATION_COMPTE', 'Validation de compte'), ('REJET_COMPTE', 'Rejet de compte'), ('VIREMENT', 'Virement'), ('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('ERREUR_SYSTEME', 'Erreur système'), ('MISE_A_JOUR_UTILISATEUR', 'Mise à jour utilisateur')], max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='visibilite',
            field=models.CharField(choices=[('MEMBRES', 'Membres'), ('AGENTS', 'Agents')], max_length=10),
        ),
    ]
