# Generated by Django 5.2.1 on 2025-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_api', '0006_remove_log_topic_alter_log_level_alter_log_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10),
        ),
    ]
