# Generated by Django 5.2.3 on 2025-06-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_api', '0009_delete_logstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='INACTIF', max_length=50)),
                ('nombre_messages', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
