# Generated by Django 5.2.1 on 2025-06-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire_id', models.IntegerField()),
                ('numero_compte', models.CharField(max_length=20, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JournalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('donnees_supplementaires', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('virement', 'Virement')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effectue_par_id', models.IntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejete', 'Rejetée')], default='en_attente', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agent_validateur_id', models.IntegerField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('compte_de_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_credit', to='fonct_app.comptebancaire')),
                ('compte_de_debit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_debit', to='fonct_app.comptebancaire')),
            ],
        ),
    ]
