# Generated by Django 5.2.3 on 2025-06-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fonct_app', '0002_alter_comptebancaire_numero_compte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalLog',
        ),
    ]
